### ISSUE TITLE
Python API 

### ISSUE THREAD

**Issue by SalemAmeen** [reedhedges/AriaCoda#13]
Hello,

I'm currently working with AriaCoda and am interested in integrating it with Python. I noticed a 'python' directory in the repository and was wondering if there is a Python API available for AriaCoda. I attempted to use it with Visual Studio 2022 but encountered some issues.

Could you provide any guidance or assistance on how to properly implement this with Python? Any help or documentation you could provide would be greatly appreciated.

Thank you for your time and assistance.

**Comment by reedhedges** [comment]
Hello,

Earlier versions of ARIA used the SWIG tool to automatically generate a Python interface to the C++ library.  I have not tested or updated this since starting the AriaCoda fork.  The Make rules and Swig interface configuration files (*.i) should still exist if you want to try fixing/updating them.   See Changes.txt for some important API differences between ARIA and AriaCoda (namely removal of some classes, and all the header files moved into a subdirectory; maybe other changes affect generation of the Python interface as well?)    Also there have probably been new releases of SWIG since then.  http://www.swig.org

**Comment by SalemAmeen** [comment]
Many thanks,

**Comment by reedhedges** [comment]
Let us know by commenting here how it goes, whether you were able to get it working, or have any questions about how the existing setup works or if you want to make any major changes or replace it.   I'll leave this issue open until we have something working, if that's OK with you?

**Comment by reedhedges** [comment]
See Issue #3 and Issue #4 as well for some older thoughts I had on this topic. We can consider those (and any others) as dependencies of this one as a meta or parent issue if you wish.

**Comment by joaocandre** [comment]
Any update on this topic?

I was trying to build using SWIG 4.3 and Python 3.13, and it fails right off the bat:

```
$ export PYTHON_INCLUDE=/usr/include/python3.13
$ export SWIG=1
$ make python
Building on Linux
#-rm -f `find python -maxdepth 1 -xtype f -name "*Aria*" | grep -v .ds | grep -v .sln | grep -v .vcproj`
cd python; 1 -Wall -c++ -python -modern -module AriaPy -DARIA_WRAPPER -Dlinux -DAREXPORT -o AriaPy_wrap.cpp -I../include ../include/Aria/wrapper.i 
/bin/sh: line 1: 1: command not found
make: *** [Makefile:484: python/AriaPy_wrap.cpp] Error 127
```

I also noticed there is no `python/AriaPy_wrap.cpp` source file, is it missing?
