### ISSUE TITLE
compilation error: invalid use of incomplete type ‘const class ArRobotConfigPacketReader’

### ISSUE THREAD

**Issue by Pedroacsilva** [reedhedges/AriaCoda#5]
Hello,

I'm attempting to build RosARIA following the instructions at http://wiki.ros.org/ROSARIA/Tutorials/How%20to%20use%20ROSARIA . When I run catkin_make, I get compilation errors: error: invalid use of incomplete type ‘const class ArRobotConfigPacketReader’, 'note: forward declaration of ‘class ArRobotConfigPacketReader’'. I believe I messed up the installation of AriaCoda, and the .h and .cpp files are in the incorrect directories. Could you please tell me how I can properly install AriaCoda?

I am working on an NVIDIA Jetson AGX Xavier, running Ubuntu 18.04

**Comment by reedhedges** [comment]
Hi Pedro, I have not tested building ROSARIA using AriaCoda for a little while, I'll try it soon.   AriaCoda can not currently be installed in /usr/local/Aria like the old ARIA was.   Adding a new installation process to AriaCoda (which will use standard Linux installation in /usr/lib or /usr/local/lib with proper library naming, etc.) has yet to be implemented.    

If you set an `ARIA` environment variable to the source code directory path for AriaCoda, ROSARIA should use that.

However -- I have just changed AriaCoda to place all header files in an Aria subdirectory (i.e. ROSARIA will need to do `#include <Aria/ArRobot>` instead of `#include "ArRobot.h"`)... and ROSARIA needs to be updated to handle this, and to work with both an old Aria library (`/usr/local/Aria`) and with AriaCoda since some users may prefer to still use an old version of ARIA.       I'm in the middle of a lot of modernizing of the codebase at the moment but I only am able to work on it occasionally in between other work.

When I have a chance I will try out ROSARIA and see what fixes need to be made.

**Comment by reedhedges** [comment]
I think that the specific problem with `ArRobotConfigPacketReader` is that I removed it from Aria.h.  `ArRobotConfigPacketReader` is really an internally used object but it's currently the only API for some robot information provided by "CONFIG" packets, so perhaps it should be in `Aria.h`?   ROSARIA can `#include "Aria/ArRobotConfigPacketReader.h"` in addition to `ArRobot.h` or `Aria.h` and it should get the full declaration.  But there will likely be other things that need to be updated as well.

**Comment by reedhedges** [comment]
I just pushed a small change to rosaria.  First, it includes "ArRobotConfigPacketReader.h" or "Aria/ArRobotConfigPacketReader.h" expliticly.  Second, it does some more checks at build to detect include file locations and it should work with just a checkout of AriaCoda by setting an `ARIA` environment variable to that directory.  (It also checks for Aria installed in /usr/local/Aria by the old Adept package, or in /usr/local/include or /usr/local/lib.)
